---
name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        name: Checkout code

      - uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb
        name: Run hassfest validation
